name: Problem issue for project cnes-vhf-stations
description: Create a problem issue for the project cnes-vhf-stations
projects: 
  - unam-transients/6
assignees:
  - alanwatsonatwork
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: Describe your problem here ...
